### ISSUE TITLE
Finding language

### ISSUE THREAD

**Issue by AlbertoDariel** [cortega26/PDF-Text-Analizer#2]
Hello, I found a small detail in the main function, and it is that it is using the parameter 'language' directly instead of searching for it in the 'languages' library. As a result, it does not filter the stop words correctly. This can be easily solved with the following addition:

if language in languages:
       mapped_language = languages [language]
else 
       print("Language not found")

then use the mapped_language as a parameter for filtered_text function

Either way you did an excellent job. I'm using the script to extract some information.
Hope you to be successful.

**Comment by cortega26** [comment]
Thank you very much for the heads-up, I updated the script with several optimizations including the correct mapping of the languages from languages.py.
